version: '3'

services:
  db:
    image: "postgres:15.3-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cats_backend_development"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db_data: {}